import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QR Gernerator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        <div className="h-screen w-full bg-[url('/qa-bg-small.jpg')] bg-cover bg-center md:bg-[url('/qa-bg.jpg')]" >
          {children}
        </div>
      </body>
    </html>
  );
}
